language: objective-c
osx_image: xcode9.2

script:
  - cd ./AXRatingViewDemo/; xcodebuild test -scheme AXRatingViewDemo -configuration Debug -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 8 Plus' | bundle exec xcpretty -c

