language: objective-c
osx_image: xcode9.2

script:
  - xcodebuild test -scheme AXRatingViewDemo -configuration Debug -destination 'platform=iOS Simulator,OS=10.12,name=iPhone 8 Plus' | bundle exec xcpretty -c

